version: '3.9'
services:
  postgres:
    image: postgres
    container_name: PostgresDB
    restart: always
    volumes:
      - ./src/app/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "pgDB"
    ports:
      - "5432:5432"